version: '3'

services:
  app:
    entrypoint: [bin/start]
    image: themaqs/gl:latest
    container_name: iasbs-gl
    env_file: .env
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:80
    volumes:
      - ./log:/usr/src/app/log
      - ./storage:/usr/src/app/storage
    links:
      - db
    networks:
      iasbs:
        ipv4_address: 10.4.0.2

  db:
    image: postgres:13.2-alpine
    container_name: iasbs-db
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./db/production:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      iasbs:
        ipv4_address: 10.4.0.3

  db-admin:
    image: dpage/pgadmin4
    container_name: db-admin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_PASSWORD=pass
      - PGADMIN_DEFAULT_EMAIL=email
    ports:
      - "8080:80"
    networks:
      iasbs:
        ipv4_address: 10.4.0.4
    volumes:
      - ./db-admin/data:/var/lib/pgadmin
      - ./db-admin/servers.json:/pgadmin4/servers.json
      - ./db-admin/pgpass:/pgpass

networks:
  iasbs:
    driver: bridge
    ipam:
      config:
        - subnet: 10.4.0.0/16


